export type CatalogPermissionSet = {
  read: string;
  create: string;
  update: string;
  activate: string;
  deactivate: string;
  lookup: string;
  export: string;
  import: string;
};

export type CatalogFieldType =
  | "text"
  | "number"
  | "boolean"
  | "date"
  | "datetime"
  | "select"
  | "lookup"
  | "textarea";

export type CatalogFieldValidation = {
  required?: boolean;
  minLength?: number;
  maxLength?: number;
  min?: number;
  max?: number;
  regex?: string;
  unique?: boolean;
  nullable?: boolean;
};

export type CatalogFieldGrid = {
  width?: number;
  align?: "left" | "center" | "right";
  format?: string;
};

export type CatalogFieldDefinition = {
  field: string;
  dbColumn?: string;
  label: string;
  type: CatalogFieldType;
  lookupCatalog?: string;
  required: boolean;
  visibleInGrid: boolean;
  visibleInForm: boolean;
  searchable: boolean;
  sortable: boolean;
  editable: boolean;
  readOnly: boolean;
  defaultValue?: string | number | boolean | null;
  placeholder?: string;
  helpText?: string;
  displayOrder: number;
  validation: CatalogFieldValidation;
  grid?: CatalogFieldGrid;
};

export type CatalogColumnMap = {
  id: string;
  tenantId: string;
  companyId?: string;
  code: string;
  name: string;
  description: string;
  isActive: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
};

export type CatalogDefinition = {
  catalogCode: string;
  displayName: string;
  tableName: string;
  idColumn: string;
  codeColumn: string;
  nameColumn: string;
  descriptionColumn?: string;
  allowedSearchColumns: readonly string[];
  allowedSortColumns: readonly string[];
  defaultSortBy: string;
  permissions: CatalogPermissionSet;
  moduleCode: string;
  tenantScoped: boolean;
  companyScoped: boolean;
  readOnly?: boolean;
  licenseRequirement?: string;
  featureFlagRequirement?: string;
  columns: CatalogColumnMap;
  fields: readonly CatalogFieldDefinition[];
};

const commonPermissions = (resource: string): CatalogPermissionSet => ({
  read: `${resource}.read`,
  create: `${resource}.create`,
  update: `${resource}.update`,
  activate: `${resource}.activate`,
  deactivate: `${resource}.deactivate`,
  lookup: `${resource}.read`,
  export: `${resource}.export`,
  import: `${resource}.import`
});

const commonCatalogFields = (companyVisible: boolean): readonly CatalogFieldDefinition[] => [
  {
    field: "code",
    label: "Code",
    type: "text",
    required: true,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    placeholder: "Enter code",
    helpText: "Unique code for this catalog and scope.",
    displayOrder: 10,
    validation: {
      required: true,
      minLength: 1,
      maxLength: 80,
      unique: true,
      nullable: false
    },
    grid: {
      width: 140,
      align: "left"
    }
  },
  {
    field: "name",
    label: "Name",
    type: "text",
    required: true,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    placeholder: "Enter name",
    displayOrder: 20,
    validation: {
      required: true,
      minLength: 1,
      maxLength: 160,
      nullable: false
    },
    grid: {
      width: 240,
      align: "left"
    }
  },
  {
    field: "description",
    label: "Description",
    type: "textarea",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: false,
    editable: true,
    readOnly: false,
    placeholder: "Optional description",
    displayOrder: 30,
    validation: {
      maxLength: 250,
      nullable: true
    },
    grid: {
      width: 320,
      align: "left"
    }
  },
  {
    field: "companyId",
    label: "Company",
    type: "lookup",
    required: companyVisible,
    visibleInGrid: companyVisible,
    visibleInForm: companyVisible,
    searchable: false,
    sortable: false,
    editable: companyVisible,
    readOnly: !companyVisible,
    displayOrder: 40,
    validation: {
      required: companyVisible,
      nullable: !companyVisible
    },
    grid: {
      width: 180,
      align: "left"
    }
  },
  {
    field: "isActive",
    label: "Active",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: true,
    displayOrder: 50,
    validation: {
      nullable: false
    },
    grid: {
      width: 96,
      align: "center",
      format: "boolean"
    }
  }
];

const unitOfMeasureFields = [
  {
    field: "code",
    label: "Codigo",
    type: "text",
    required: true,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    placeholder: "UND",
    displayOrder: 10,
    validation: { required: true, minLength: 1, maxLength: 40, unique: true, nullable: false },
    grid: { width: 120, align: "left" }
  },
  {
    field: "name",
    label: "Nombre",
    type: "text",
    required: true,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    placeholder: "Unidad",
    displayOrder: 20,
    validation: { required: true, minLength: 1, maxLength: 160, nullable: false },
    grid: { width: 220, align: "left" }
  },
  {
    field: "description",
    label: "Descripcion",
    type: "textarea",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: false,
    editable: true,
    readOnly: false,
    placeholder: "Descripcion opcional",
    displayOrder: 30,
    validation: { maxLength: 250, nullable: true },
    grid: { width: 280, align: "left" }
  },
  {
    field: "symbol",
    dbColumn: "Symbol",
    label: "Simbolo",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: false,
    editable: true,
    readOnly: false,
    placeholder: "u",
    displayOrder: 40,
    validation: { maxLength: 20, nullable: true },
    grid: { width: 100, align: "left" }
  },
  {
    field: "unitType",
    dbColumn: "UnitType",
    label: "Tipo de unidad",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    placeholder: "QUANTITY",
    helpText: "QUANTITY, WEIGHT, VOLUME, LENGTH, TIME, SERVICE",
    displayOrder: 50,
    validation: { maxLength: 40, nullable: true },
    grid: { width: 140, align: "left" }
  },
  {
    field: "decimalPrecision",
    dbColumn: "DecimalPrecision",
    label: "Precision decimal",
    type: "number",
    required: true,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    defaultValue: 2,
    displayOrder: 60,
    validation: { required: true, min: 0, max: 6, nullable: false },
    grid: { width: 130, align: "right" }
  },
  {
    field: "isBaseUnit",
    dbColumn: "IsBaseUnit",
    label: "Unidad base",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    defaultValue: false,
    displayOrder: 70,
    validation: { nullable: false },
    grid: { width: 120, align: "center", format: "boolean" }
  },
  {
    field: "isActive",
    label: "Activo",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: true,
    displayOrder: 80,
    validation: { nullable: false },
    grid: { width: 96, align: "center", format: "boolean" }
  }
] as const satisfies readonly CatalogFieldDefinition[];

const warehouseFields = [
  {
    field: "code",
    label: "Codigo",
    type: "text",
    required: true,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    placeholder: "ALM-PRINCIPAL",
    displayOrder: 10,
    validation: { required: true, minLength: 1, maxLength: 40, unique: true, nullable: false },
    grid: { width: 140, align: "left" }
  },
  {
    field: "name",
    label: "Nombre",
    type: "text",
    required: true,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    placeholder: "Almacen principal",
    displayOrder: 20,
    validation: { required: true, minLength: 1, maxLength: 160, nullable: false },
    grid: { width: 220, align: "left" }
  },
  {
    field: "description",
    label: "Descripcion",
    type: "textarea",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: false,
    editable: true,
    readOnly: false,
    placeholder: "Descripcion opcional",
    displayOrder: 30,
    validation: { maxLength: 250, nullable: true },
    grid: { width: 280, align: "left" }
  },
  {
    field: "warehouseType",
    dbColumn: "WarehouseType",
    label: "Tipo almacen",
    type: "text",
    required: true,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: "NORMAL",
    helpText: "NORMAL, PRODUCTION, CONSIGNMENT, TRANSIT, VIRTUAL",
    displayOrder: 40,
    validation: {
      required: true,
      maxLength: 40,
      regex: "^(NORMAL|PRODUCTION|CONSIGNMENT|TRANSIT|VIRTUAL)$",
      nullable: false
    },
    grid: { width: 150, align: "left" }
  },
  {
    field: "addressLine1",
    dbColumn: "AddressLine1",
    label: "Direccion 1",
    type: "text",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 50,
    validation: { maxLength: 250, nullable: true }
  },
  {
    field: "addressLine2",
    dbColumn: "AddressLine2",
    label: "Direccion 2",
    type: "text",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 60,
    validation: { maxLength: 250, nullable: true }
  },
  {
    field: "city",
    dbColumn: "City",
    label: "Ciudad",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 70,
    validation: { maxLength: 120, nullable: true },
    grid: { width: 150, align: "left" }
  },
  {
    field: "province",
    dbColumn: "Province",
    label: "Provincia",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 80,
    validation: { maxLength: 120, nullable: true },
    grid: { width: 150, align: "left" }
  },
  {
    field: "countryCode",
    dbColumn: "CountryCode",
    label: "Pais",
    type: "text",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    placeholder: "DOM",
    displayOrder: 90,
    validation: { maxLength: 3, nullable: true }
  },
  {
    field: "responsibleUserId",
    dbColumn: "ResponsibleUserId",
    label: "Responsable",
    type: "lookup",
    required: false,
    visibleInGrid: false,
    visibleInForm: false,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 100,
    validation: { nullable: true }
  },
  {
    field: "allowsNegativeInventory",
    dbColumn: "AllowsNegativeInventory",
    label: "Permite negativo",
    type: "boolean",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    defaultValue: false,
    displayOrder: 110,
    validation: { nullable: false }
  },
  {
    field: "isDefault",
    dbColumn: "IsDefault",
    label: "Predeterminado",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    defaultValue: false,
    displayOrder: 120,
    validation: { nullable: false },
    grid: { width: 130, align: "center", format: "boolean" }
  },
  {
    field: "isTransit",
    dbColumn: "IsTransit",
    label: "Transito",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    defaultValue: false,
    displayOrder: 130,
    validation: { nullable: false },
    grid: { width: 110, align: "center", format: "boolean" }
  },
  {
    field: "isVirtual",
    dbColumn: "IsVirtual",
    label: "Virtual",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    defaultValue: false,
    displayOrder: 140,
    validation: { nullable: false },
    grid: { width: 100, align: "center", format: "boolean" }
  },
  {
    field: "isActive",
    label: "Activo",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: true,
    displayOrder: 150,
    validation: { nullable: false },
    grid: { width: 96, align: "center", format: "boolean" }
  }
] as const satisfies readonly CatalogFieldDefinition[];

const inventoryStockFields = [
  {
    field: "itemCode",
    dbColumn: "ItemCode",
    label: "Articulo",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 10,
    validation: { nullable: true },
    grid: { width: 130, align: "left" }
  },
  {
    field: "itemDescription",
    dbColumn: "ItemDescription",
    label: "Descripcion articulo",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 20,
    validation: { nullable: true },
    grid: { width: 260, align: "left" }
  },
  {
    field: "warehouseCode",
    dbColumn: "WarehouseCode",
    label: "Almacen",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 30,
    validation: { nullable: true },
    grid: { width: 140, align: "left" }
  },
  {
    field: "warehouseName",
    dbColumn: "WarehouseName",
    label: "Nombre almacen",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 40,
    validation: { nullable: true },
    grid: { width: 220, align: "left" }
  },
  {
    field: "quantityOnHand",
    dbColumn: "QuantityOnHand",
    label: "Existencia",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 50,
    validation: { min: 0, nullable: false },
    grid: { width: 130, align: "right" }
  },
  {
    field: "quantityReserved",
    dbColumn: "QuantityReserved",
    label: "Reservado",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 60,
    validation: { min: 0, nullable: false },
    grid: { width: 130, align: "right" }
  },
  {
    field: "quantityAvailable",
    dbColumn: "QuantityAvailable",
    label: "Disponible",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 70,
    validation: { min: 0, nullable: false },
    grid: { width: 130, align: "right" }
  },
  {
    field: "averageCost",
    dbColumn: "AverageCost",
    label: "Costo promedio",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 80,
    validation: { min: 0, nullable: false },
    grid: { width: 140, align: "right", format: "currency" }
  },
  {
    field: "lastCost",
    dbColumn: "LastCost",
    label: "Ultimo costo",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 90,
    validation: { min: 0, nullable: false },
    grid: { width: 130, align: "right", format: "currency" }
  },
  {
    field: "standardCost",
    dbColumn: "StandardCost",
    label: "Costo estandar",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 100,
    validation: { min: 0, nullable: false },
    grid: { width: 140, align: "right", format: "currency" }
  },
  {
    field: "lastMovementAt",
    dbColumn: "LastMovementAt",
    label: "Ultimo movimiento",
    type: "datetime",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 110,
    validation: { nullable: true },
    grid: { width: 160, align: "left" }
  },
  {
    field: "isActive",
    label: "Activo",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: true,
    editable: false,
    readOnly: true,
    defaultValue: true,
    displayOrder: 120,
    validation: { nullable: false },
    grid: { width: 96, align: "center", format: "boolean" }
  }
] as const satisfies readonly CatalogFieldDefinition[];

const inventoryMovementFields = [
  {
    field: "movementNumber",
    dbColumn: "MovementNumber",
    label: "Movimiento",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 10,
    validation: { nullable: false },
    grid: { width: 150, align: "left" }
  },
  {
    field: "movementType",
    dbColumn: "MovementType",
    label: "Tipo",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 20,
    validation: { nullable: false },
    grid: { width: 190, align: "left" }
  },
  {
    field: "movementDate",
    dbColumn: "MovementDate",
    label: "Fecha",
    type: "datetime",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 30,
    validation: { nullable: false },
    grid: { width: 170, align: "left" }
  },
  {
    field: "status",
    dbColumn: "Status",
    label: "Estado",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 40,
    validation: { nullable: false },
    grid: { width: 110, align: "left" }
  },
  {
    field: "sourceModule",
    dbColumn: "SourceModule",
    label: "Modulo origen",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 50,
    validation: { nullable: true },
    grid: { width: 140, align: "left" }
  },
  {
    field: "sourceDocumentNumber",
    dbColumn: "SourceDocumentNumber",
    label: "Documento origen",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 60,
    validation: { nullable: true },
    grid: { width: 170, align: "left" }
  },
  {
    field: "reference",
    dbColumn: "Reference",
    label: "Referencia",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 70,
    validation: { nullable: true },
    grid: { width: 180, align: "left" }
  },
  {
    field: "lineCount",
    dbColumn: "LineCount",
    label: "Lineas",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 80,
    validation: { min: 0, nullable: false },
    grid: { width: 90, align: "right" }
  },
  {
    field: "totalQuantity",
    dbColumn: "TotalQuantity",
    label: "Cantidad total",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 90,
    validation: { min: 0, nullable: false },
    grid: { width: 140, align: "right" }
  },
  {
    field: "totalCost",
    dbColumn: "TotalCost",
    label: "Costo total",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 100,
    validation: { min: 0, nullable: false },
    grid: { width: 130, align: "right", format: "currency" }
  },
  {
    field: "postedAt",
    dbColumn: "PostedAt",
    label: "Posteado",
    type: "datetime",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 110,
    validation: { nullable: true },
    grid: { width: 160, align: "left" }
  },
  {
    field: "voidedAt",
    dbColumn: "VoidedAt",
    label: "Anulado",
    type: "datetime",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 120,
    validation: { nullable: true },
    grid: { width: 160, align: "left" }
  },
  {
    field: "isActive",
    label: "Activo",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: false,
    editable: false,
    readOnly: true,
    defaultValue: true,
    displayOrder: 130,
    validation: { nullable: false },
    grid: { width: 96, align: "center", format: "boolean" }
  }
] as const satisfies readonly CatalogFieldDefinition[];

const inventoryMovementLineFields = [
  {
    field: "movementNumber",
    dbColumn: "MovementNumber",
    label: "Movimiento",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 10,
    validation: { nullable: false },
    grid: { width: 150, align: "left" }
  },
  {
    field: "movementType",
    dbColumn: "MovementType",
    label: "Tipo",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 20,
    validation: { nullable: false },
    grid: { width: 190, align: "left" }
  },
  {
    field: "status",
    dbColumn: "Status",
    label: "Estado",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 30,
    validation: { nullable: false },
    grid: { width: 110, align: "left" }
  },
  {
    field: "lineNumber",
    dbColumn: "LineNumber",
    label: "Linea",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 40,
    validation: { min: 1, nullable: false },
    grid: { width: 90, align: "right" }
  },
  {
    field: "itemCode",
    dbColumn: "ItemCode",
    label: "Articulo",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 50,
    validation: { nullable: false },
    grid: { width: 130, align: "left" }
  },
  {
    field: "itemDescription",
    dbColumn: "ItemDescription",
    label: "Descripcion articulo",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 60,
    validation: { nullable: true },
    grid: { width: 260, align: "left" }
  },
  {
    field: "warehouseCode",
    dbColumn: "WarehouseCode",
    label: "Almacen",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 70,
    validation: { nullable: false },
    grid: { width: 140, align: "left" }
  },
  {
    field: "quantity",
    dbColumn: "Quantity",
    label: "Cantidad",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 80,
    validation: { min: 0, nullable: false },
    grid: { width: 120, align: "right" }
  },
  {
    field: "unitCost",
    dbColumn: "UnitCost",
    label: "Costo unitario",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 90,
    validation: { min: 0, nullable: false },
    grid: { width: 140, align: "right", format: "currency" }
  },
  {
    field: "totalCost",
    dbColumn: "TotalCost",
    label: "Costo total",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 100,
    validation: { min: 0, nullable: false },
    grid: { width: 130, align: "right", format: "currency" }
  },
  {
    field: "lotNumber",
    dbColumn: "LotNumber",
    label: "Lote",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 110,
    validation: { nullable: true },
    grid: { width: 130, align: "left" }
  },
  {
    field: "serialNumber",
    dbColumn: "SerialNumber",
    label: "Serie",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 120,
    validation: { nullable: true },
    grid: { width: 130, align: "left" }
  },
  {
    field: "expirationDate",
    dbColumn: "ExpirationDate",
    label: "Vencimiento",
    type: "date",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 130,
    validation: { nullable: true },
    grid: { width: 130, align: "left" }
  }
] as const satisfies readonly CatalogFieldDefinition[];

const inventoryLedgerFields = [
  {
    field: "movementNumber",
    dbColumn: "MovementNumber",
    label: "Movimiento",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 10,
    validation: { nullable: false },
    grid: { width: 150, align: "left" }
  },
  {
    field: "movementType",
    dbColumn: "MovementType",
    label: "Tipo",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 20,
    validation: { nullable: false },
    grid: { width: 180, align: "left" }
  },
  {
    field: "ledgerDirection",
    dbColumn: "LedgerDirection",
    label: "Direccion",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 30,
    validation: { nullable: false },
    grid: { width: 110, align: "center" }
  },
  {
    field: "movementDate",
    dbColumn: "MovementDate",
    label: "Fecha",
    type: "datetime",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 40,
    validation: { nullable: false },
    grid: { width: 170, align: "left" }
  },
  {
    field: "postedAt",
    dbColumn: "PostedAt",
    label: "Posteado",
    type: "datetime",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 50,
    validation: { nullable: false },
    grid: { width: 170, align: "left" }
  },
  {
    field: "itemCode",
    dbColumn: "ItemCode",
    label: "Articulo",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 60,
    validation: { nullable: false },
    grid: { width: 130, align: "left" }
  },
  {
    field: "itemDescription",
    dbColumn: "ItemDescription",
    label: "Descripcion articulo",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 70,
    validation: { nullable: true },
    grid: { width: 240, align: "left" }
  },
  {
    field: "warehouseCode",
    dbColumn: "WarehouseCode",
    label: "Almacen",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 80,
    validation: { nullable: false },
    grid: { width: 130, align: "left" }
  },
  {
    field: "warehouseName",
    dbColumn: "WarehouseName",
    label: "Nombre almacen",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 90,
    validation: { nullable: true },
    grid: { width: 200, align: "left" }
  },
  {
    field: "quantityIn",
    dbColumn: "QuantityIn",
    label: "Entrada",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 100,
    validation: { min: 0, nullable: false },
    grid: { width: 110, align: "right" }
  },
  {
    field: "quantityOut",
    dbColumn: "QuantityOut",
    label: "Salida",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 110,
    validation: { min: 0, nullable: false },
    grid: { width: 110, align: "right" }
  },
  {
    field: "quantityBalanceImpact",
    dbColumn: "QuantityBalanceImpact",
    label: "Impacto",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 120,
    validation: { nullable: false },
    grid: { width: 120, align: "right" }
  },
  {
    field: "unitCost",
    dbColumn: "UnitCost",
    label: "Costo unitario",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 130,
    validation: { min: 0, nullable: false },
    grid: { width: 140, align: "right", format: "currency" }
  },
  {
    field: "totalCost",
    dbColumn: "TotalCost",
    label: "Costo total",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: false,
    sortable: true,
    editable: false,
    readOnly: true,
    displayOrder: 140,
    validation: { min: 0, nullable: false },
    grid: { width: 130, align: "right", format: "currency" }
  },
  {
    field: "sourceDocumentNumber",
    dbColumn: "SourceDocumentNumber",
    label: "Documento origen",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 150,
    validation: { nullable: true },
    grid: { width: 170, align: "left" }
  },
  {
    field: "reference",
    dbColumn: "Reference",
    label: "Referencia",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: false,
    searchable: true,
    sortable: false,
    editable: false,
    readOnly: true,
    displayOrder: 160,
    validation: { nullable: true },
    grid: { width: 180, align: "left" }
  }
] as const satisfies readonly CatalogFieldDefinition[];

const customerFields = [
  {
    field: "code",
    label: "Codigo",
    type: "text",
    required: true,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    placeholder: "CLI-0001",
    displayOrder: 10,
    validation: { required: true, minLength: 1, maxLength: 40, unique: true, nullable: false },
    grid: { width: 120, align: "left" }
  },
  {
    field: "name",
    label: "Nombre",
    type: "text",
    required: true,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    placeholder: "Nombre legal del cliente",
    displayOrder: 20,
    validation: { required: true, minLength: 1, maxLength: 200, nullable: false },
    grid: { width: 240, align: "left" }
  },
  {
    field: "commercialName",
    dbColumn: "CommercialName",
    label: "Nombre comercial",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    displayOrder: 30,
    validation: { maxLength: 200, nullable: true },
    grid: { width: 220, align: "left" }
  },
  {
    field: "documentType",
    dbColumn: "DocumentType",
    label: "Tipo documento",
    type: "text",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    placeholder: "RNC, Cedula, Pasaporte",
    displayOrder: 40,
    validation: { maxLength: 30, nullable: true }
  },
  {
    field: "documentNumber",
    dbColumn: "DocumentNumber",
    label: "Documento",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    displayOrder: 50,
    validation: { maxLength: 40, nullable: true },
    grid: { width: 150, align: "left" }
  },
  {
    field: "email",
    dbColumn: "Email",
    label: "Correo",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    displayOrder: 60,
    validation: { maxLength: 200, regex: "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$", nullable: true },
    grid: { width: 220, align: "left" }
  },
  {
    field: "phone",
    dbColumn: "Phone",
    label: "Telefono",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 70,
    validation: { maxLength: 40, nullable: true },
    grid: { width: 140, align: "left" }
  },
  {
    field: "mobile",
    dbColumn: "Mobile",
    label: "Movil",
    type: "text",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 80,
    validation: { maxLength: 40, nullable: true }
  },
  {
    field: "addressLine1",
    dbColumn: "AddressLine1",
    label: "Direccion",
    type: "textarea",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 90,
    validation: { maxLength: 300, nullable: true }
  },
  {
    field: "city",
    dbColumn: "City",
    label: "Ciudad",
    type: "text",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    displayOrder: 100,
    validation: { maxLength: 120, nullable: true }
  },
  {
    field: "province",
    dbColumn: "Province",
    label: "Provincia",
    type: "text",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    displayOrder: 110,
    validation: { maxLength: 120, nullable: true }
  },
  {
    field: "countryCode",
    dbColumn: "CountryCode",
    label: "Pais",
    type: "text",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    placeholder: "DOM",
    displayOrder: 120,
    validation: { minLength: 2, maxLength: 3, nullable: true }
  },
  {
    field: "paymentTermId",
    dbColumn: "PaymentTermId",
    label: "Condicion de pago",
    type: "lookup",
    lookupCatalog: "payment-terms",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 130,
    validation: { nullable: true }
  },
  {
    field: "currencyId",
    dbColumn: "CurrencyId",
    label: "Moneda",
    type: "lookup",
    lookupCatalog: "currencies",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 140,
    validation: { nullable: true }
  },
  {
    field: "taxCategoryId",
    dbColumn: "TaxCategoryId",
    label: "Categoria fiscal",
    type: "lookup",
    lookupCatalog: "tax-categories",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 150,
    validation: { nullable: true }
  },
  {
    field: "creditLimit",
    dbColumn: "CreditLimit",
    label: "Limite de credito",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: 0,
    displayOrder: 160,
    validation: { min: 0, nullable: true },
    grid: { width: 140, align: "right", format: "currency" }
  },
  {
    field: "isCreditCustomer",
    dbColumn: "IsCreditCustomer",
    label: "Cliente a credito",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: false,
    displayOrder: 170,
    validation: { nullable: false },
    grid: { width: 120, align: "center", format: "boolean" }
  },
  {
    field: "isActive",
    label: "Activo",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: true,
    displayOrder: 180,
    validation: { nullable: false },
    grid: { width: 96, align: "center", format: "boolean" }
  }
] as const satisfies readonly CatalogFieldDefinition[];

const supplierFields = [
  {
    field: "code",
    label: "Codigo",
    type: "text",
    required: true,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    placeholder: "SUP-0001",
    displayOrder: 10,
    validation: { required: true, minLength: 1, maxLength: 40, unique: true, nullable: false },
    grid: { width: 120, align: "left" }
  },
  {
    field: "name",
    label: "Nombre",
    type: "text",
    required: true,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    placeholder: "Nombre legal del proveedor",
    displayOrder: 20,
    validation: { required: true, minLength: 1, maxLength: 200, nullable: false },
    grid: { width: 240, align: "left" }
  },
  {
    field: "commercialName",
    dbColumn: "CommercialName",
    label: "Nombre comercial",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    displayOrder: 30,
    validation: { maxLength: 200, nullable: true },
    grid: { width: 220, align: "left" }
  },
  {
    field: "documentType",
    dbColumn: "DocumentType",
    label: "Tipo documento",
    type: "text",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    placeholder: "RNC, Cedula, Pasaporte",
    displayOrder: 40,
    validation: { maxLength: 30, nullable: true }
  },
  {
    field: "documentNumber",
    dbColumn: "DocumentNumber",
    label: "Documento",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    displayOrder: 50,
    validation: { maxLength: 40, nullable: true },
    grid: { width: 150, align: "left" }
  },
  {
    field: "email",
    dbColumn: "Email",
    label: "Correo",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    displayOrder: 60,
    validation: { maxLength: 200, regex: "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$", nullable: true },
    grid: { width: 220, align: "left" }
  },
  {
    field: "phone",
    dbColumn: "Phone",
    label: "Telefono",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 70,
    validation: { maxLength: 40, nullable: true },
    grid: { width: 140, align: "left" }
  },
  {
    field: "mobile",
    dbColumn: "Mobile",
    label: "Movil",
    type: "text",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 80,
    validation: { maxLength: 40, nullable: true }
  },
  {
    field: "addressLine1",
    dbColumn: "AddressLine1",
    label: "Direccion",
    type: "textarea",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 90,
    validation: { maxLength: 300, nullable: true }
  },
  {
    field: "city",
    dbColumn: "City",
    label: "Ciudad",
    type: "text",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    displayOrder: 100,
    validation: { maxLength: 120, nullable: true }
  },
  {
    field: "province",
    dbColumn: "Province",
    label: "Provincia",
    type: "text",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    displayOrder: 110,
    validation: { maxLength: 120, nullable: true }
  },
  {
    field: "countryCode",
    dbColumn: "CountryCode",
    label: "Pais",
    type: "text",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    placeholder: "DOM",
    displayOrder: 120,
    validation: { minLength: 2, maxLength: 3, nullable: true }
  },
  {
    field: "paymentTermId",
    dbColumn: "PaymentTermId",
    label: "Condicion de pago",
    type: "lookup",
    lookupCatalog: "payment-terms",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 130,
    validation: { nullable: true }
  },
  {
    field: "currencyId",
    dbColumn: "CurrencyId",
    label: "Moneda",
    type: "lookup",
    lookupCatalog: "currencies",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 140,
    validation: { nullable: true }
  },
  {
    field: "taxCategoryId",
    dbColumn: "TaxCategoryId",
    label: "Categoria fiscal",
    type: "lookup",
    lookupCatalog: "tax-categories",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 150,
    validation: { nullable: true }
  },
  {
    field: "isTaxWithholder",
    dbColumn: "IsTaxWithholder",
    label: "Agente de retencion",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: false,
    displayOrder: 160,
    validation: { nullable: false },
    grid: { width: 130, align: "center", format: "boolean" }
  },
  {
    field: "isForeignSupplier",
    dbColumn: "IsForeignSupplier",
    label: "Proveedor extranjero",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: false,
    displayOrder: 170,
    validation: { nullable: false },
    grid: { width: 150, align: "center", format: "boolean" }
  },
  {
    field: "contactName",
    dbColumn: "ContactName",
    label: "Contacto",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    displayOrder: 180,
    validation: { maxLength: 200, nullable: true },
    grid: { width: 200, align: "left" }
  },
  {
    field: "contactEmail",
    dbColumn: "ContactEmail",
    label: "Correo contacto",
    type: "text",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 190,
    validation: { maxLength: 200, regex: "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$", nullable: true }
  },
  {
    field: "contactPhone",
    dbColumn: "ContactPhone",
    label: "Telefono contacto",
    type: "text",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 200,
    validation: { maxLength: 40, nullable: true }
  },
  {
    field: "notes",
    dbColumn: "Notes",
    label: "Notas",
    type: "textarea",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 210,
    validation: { maxLength: 500, nullable: true }
  },
  {
    field: "isActive",
    label: "Activo",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: true,
    displayOrder: 220,
    validation: { nullable: false },
    grid: { width: 96, align: "center", format: "boolean" }
  }
] as const satisfies readonly CatalogFieldDefinition[];

const categoryFields = [
  {
    field: "code",
    label: "Codigo",
    type: "text",
    required: true,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    placeholder: "CAT-0001",
    displayOrder: 10,
    validation: { required: true, minLength: 1, maxLength: 40, unique: true, nullable: false },
    grid: { width: 120, align: "left" }
  },
  {
    field: "name",
    label: "Nombre",
    type: "text",
    required: true,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    placeholder: "Nombre de la categoria",
    displayOrder: 20,
    validation: { required: true, minLength: 1, maxLength: 160, nullable: false },
    grid: { width: 220, align: "left" }
  },
  {
    field: "description",
    label: "Descripcion",
    type: "textarea",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 30,
    validation: { maxLength: 250, nullable: true },
    grid: { width: 280, align: "left" }
  },
  {
    field: "parentCategoryId",
    dbColumn: "ParentCategoryId",
    label: "Categoria padre",
    type: "lookup",
    lookupCatalog: "categories",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    displayOrder: 40,
    validation: { nullable: true }
  },
  {
    field: "isSalesCategory",
    dbColumn: "IsSalesCategory",
    label: "Categoria de ventas",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: true,
    displayOrder: 50,
    validation: { nullable: false },
    grid: { width: 130, align: "center", format: "boolean" }
  },
  {
    field: "isPurchaseCategory",
    dbColumn: "IsPurchaseCategory",
    label: "Categoria de compras",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: true,
    displayOrder: 60,
    validation: { nullable: false },
    grid: { width: 140, align: "center", format: "boolean" }
  },
  {
    field: "isInventoryCategory",
    dbColumn: "IsInventoryCategory",
    label: "Categoria de inventario",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: true,
    displayOrder: 70,
    validation: { nullable: false },
    grid: { width: 150, align: "center", format: "boolean" }
  },
  {
    field: "isActive",
    label: "Activo",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: true,
    displayOrder: 80,
    validation: { nullable: false },
    grid: { width: 96, align: "center", format: "boolean" }
  }
] as const satisfies readonly CatalogFieldDefinition[];

const brandFields = [
  {
    field: "code",
    label: "Codigo",
    type: "text",
    required: true,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    placeholder: "MAR-0001",
    displayOrder: 10,
    validation: { required: true, minLength: 1, maxLength: 40, unique: true, nullable: false },
    grid: { width: 120, align: "left" }
  },
  {
    field: "name",
    label: "Nombre",
    type: "text",
    required: true,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    placeholder: "Nombre de la marca",
    displayOrder: 20,
    validation: { required: true, minLength: 1, maxLength: 160, nullable: false },
    grid: { width: 220, align: "left" }
  },
  {
    field: "description",
    label: "Descripcion",
    type: "textarea",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 30,
    validation: { maxLength: 250, nullable: true },
    grid: { width: 280, align: "left" }
  },
  {
    field: "website",
    dbColumn: "Website",
    label: "Sitio web",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 40,
    validation: { maxLength: 250, nullable: true },
    grid: { width: 220, align: "left" }
  },
  {
    field: "countryCode",
    dbColumn: "CountryCode",
    label: "Pais",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    placeholder: "DOM",
    displayOrder: 50,
    validation: { maxLength: 3, nullable: true },
    grid: { width: 90, align: "left" }
  },
  {
    field: "isActive",
    label: "Activo",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: true,
    displayOrder: 60,
    validation: { nullable: false },
    grid: { width: 96, align: "center", format: "boolean" }
  }
] as const satisfies readonly CatalogFieldDefinition[];

const itemFields = [
  {
    field: "code",
    label: "Codigo",
    type: "text",
    required: true,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    placeholder: "ART-0001",
    displayOrder: 10,
    validation: { required: true, minLength: 1, maxLength: 50, unique: true, nullable: false },
    grid: { width: 130, align: "left" }
  },
  {
    field: "name",
    label: "Descripcion",
    type: "text",
    required: true,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    placeholder: "Descripcion principal del articulo",
    displayOrder: 20,
    validation: { required: true, minLength: 1, maxLength: 300, nullable: false },
    grid: { width: 280, align: "left" }
  },
  {
    field: "shortDescription",
    dbColumn: "ShortDescription",
    label: "Descripcion corta",
    type: "text",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 30,
    validation: { maxLength: 120, nullable: true }
  },
  {
    field: "barcode",
    dbColumn: "Barcode",
    label: "Codigo de barras",
    type: "text",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    displayOrder: 40,
    validation: { maxLength: 100, nullable: true },
    grid: { width: 170, align: "left" }
  },
  {
    field: "alternateCode",
    dbColumn: "AlternateCode",
    label: "Codigo alterno",
    type: "text",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: true,
    sortable: true,
    editable: true,
    readOnly: false,
    displayOrder: 50,
    validation: { maxLength: 100, nullable: true }
  },
  {
    field: "categoryId",
    dbColumn: "CategoryId",
    label: "Categoria",
    type: "lookup",
    lookupCatalog: "categories",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    displayOrder: 60,
    validation: { nullable: true },
    grid: { width: 150, align: "left" }
  },
  {
    field: "brandId",
    dbColumn: "BrandId",
    label: "Marca",
    type: "lookup",
    lookupCatalog: "brands",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    displayOrder: 70,
    validation: { nullable: true },
    grid: { width: 150, align: "left" }
  },
  {
    field: "unitOfMeasureId",
    dbColumn: "UnitOfMeasureId",
    label: "Unidad",
    type: "lookup",
    lookupCatalog: "units-of-measure",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 80,
    validation: { nullable: true },
    grid: { width: 130, align: "left" }
  },
  {
    field: "taxCategoryId",
    dbColumn: "TaxCategoryId",
    label: "Categoria fiscal",
    type: "lookup",
    lookupCatalog: "tax-categories",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 90,
    validation: { nullable: true }
  },
  {
    field: "defaultWarehouseId",
    dbColumn: "DefaultWarehouseId",
    label: "Almacen por defecto",
    type: "lookup",
    lookupCatalog: "warehouses",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 95,
    validation: { nullable: true }
  },
  {
    field: "inventoryType",
    dbColumn: "InventoryType",
    label: "Tipo inventario",
    type: "text",
    required: true,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: "PRODUCT",
    helpText: "PRODUCT, SERVICE, RAW_MATERIAL, FINISHED_GOOD, CONSUMABLE",
    displayOrder: 100,
    validation: {
      required: true,
      regex: "^(PRODUCT|SERVICE|RAW_MATERIAL|FINISHED_GOOD|CONSUMABLE)$",
      nullable: false
    }
  },
  {
    field: "itemType",
    dbColumn: "ItemType",
    label: "Tipo articulo",
    type: "text",
    required: true,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: "NORMAL",
    helpText: "NORMAL, KIT, BUNDLE, SERVICE",
    displayOrder: 110,
    validation: { required: true, regex: "^(NORMAL|KIT|BUNDLE|SERVICE)$", nullable: false }
  },
  {
    field: "allowNegativeInventory",
    dbColumn: "AllowNegativeInventory",
    label: "Permite negativo",
    type: "boolean",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    defaultValue: false,
    displayOrder: 120,
    validation: { nullable: false }
  },
  {
    field: "trackInventory",
    dbColumn: "TrackInventory",
    label: "Controla inventario",
    type: "boolean",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: true,
    displayOrder: 130,
    validation: { nullable: false }
  },
  {
    field: "trackLot",
    dbColumn: "TrackLot",
    label: "Controla lote",
    type: "boolean",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    defaultValue: false,
    displayOrder: 140,
    validation: { nullable: false }
  },
  {
    field: "trackSerial",
    dbColumn: "TrackSerial",
    label: "Controla serie",
    type: "boolean",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    defaultValue: false,
    displayOrder: 150,
    validation: { nullable: false }
  },
  {
    field: "isService",
    dbColumn: "IsService",
    label: "Es servicio",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: false,
    displayOrder: 160,
    validation: { nullable: false },
    grid: { width: 110, align: "center", format: "boolean" }
  },
  {
    field: "isManufactured",
    dbColumn: "IsManufactured",
    label: "Manufacturado",
    type: "boolean",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: false,
    displayOrder: 170,
    validation: { nullable: false }
  },
  {
    field: "costMethod",
    dbColumn: "CostMethod",
    label: "Metodo de costo",
    type: "text",
    required: true,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: "AVERAGE",
    helpText: "AVERAGE, FIFO, LIFO_PLACEHOLDER, STANDARD",
    displayOrder: 180,
    validation: { required: true, regex: "^(AVERAGE|FIFO|LIFO_PLACEHOLDER|STANDARD)$", nullable: false }
  },
  {
    field: "standardCost",
    dbColumn: "StandardCost",
    label: "Costo estandar",
    type: "number",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: 0,
    displayOrder: 190,
    validation: { min: 0, nullable: true }
  },
  {
    field: "averageCost",
    dbColumn: "AverageCost",
    label: "Costo promedio",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: 0,
    displayOrder: 200,
    validation: { min: 0, nullable: true },
    grid: { width: 140, align: "right", format: "currency" }
  },
  {
    field: "lastCost",
    dbColumn: "LastCost",
    label: "Ultimo costo",
    type: "number",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: 0,
    displayOrder: 210,
    validation: { min: 0, nullable: true }
  },
  {
    field: "basePrice",
    dbColumn: "BasePrice",
    label: "Precio base",
    type: "number",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: 0,
    displayOrder: 220,
    validation: { min: 0, nullable: true },
    grid: { width: 140, align: "right", format: "currency" }
  },
  {
    field: "minimumPrice",
    dbColumn: "MinimumPrice",
    label: "Precio minimo",
    type: "number",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: 0,
    displayOrder: 230,
    validation: { min: 0, nullable: true }
  },
  {
    field: "maximumDiscountPercent",
    dbColumn: "MaximumDiscountPercent",
    label: "Descuento maximo %",
    type: "number",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: 0,
    displayOrder: 240,
    validation: { min: 0, max: 100, nullable: true }
  },
  {
    field: "weight",
    dbColumn: "Weight",
    label: "Peso",
    type: "number",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    defaultValue: 0,
    displayOrder: 250,
    validation: { min: 0, nullable: true }
  },
  {
    field: "volume",
    dbColumn: "Volume",
    label: "Volumen",
    type: "number",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    defaultValue: 0,
    displayOrder: 260,
    validation: { min: 0, nullable: true }
  },
  {
    field: "imageUrl",
    dbColumn: "ImageUrl",
    label: "URL imagen",
    type: "text",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 270,
    validation: { maxLength: 500, nullable: true }
  },
  {
    field: "notes",
    dbColumn: "Notes",
    label: "Notas",
    type: "textarea",
    required: false,
    visibleInGrid: false,
    visibleInForm: true,
    searchable: false,
    sortable: false,
    editable: true,
    readOnly: false,
    displayOrder: 280,
    validation: { maxLength: 1000, nullable: true }
  },
  {
    field: "isActive",
    label: "Activo",
    type: "boolean",
    required: false,
    visibleInGrid: true,
    visibleInForm: true,
    searchable: false,
    sortable: true,
    editable: true,
    readOnly: false,
    defaultValue: true,
    displayOrder: 290,
    validation: { nullable: false },
    grid: { width: 96, align: "center", format: "boolean" }
  }
] as const satisfies readonly CatalogFieldDefinition[];

export const catalogDefinitions = {
  currencies: {
    catalogCode: "currencies",
    displayName: "Currencies",
    tableName: "core.Currencies",
    idColumn: "CurrencyId",
    codeColumn: "Code",
    nameColumn: "Name",
    descriptionColumn: "Description",
    allowedSearchColumns: ["Code", "Name", "Description"],
    allowedSortColumns: ["Code", "Name", "CreatedAt", "IsActive"],
    defaultSortBy: "Name",
    permissions: commonPermissions("master-data.currencies"),
    moduleCode: "master-data",
    tenantScoped: true,
    companyScoped: false,
    columns: {
      id: "CurrencyId",
      tenantId: "TenantId",
      companyId: "CompanyId",
      code: "Code",
      name: "Name",
      description: "Description",
      isActive: "IsActive",
      createdAt: "CreatedAt",
      updatedAt: "UpdatedAt",
      createdBy: "CreatedBy",
      updatedBy: "UpdatedBy"
    },
    fields: commonCatalogFields(false)
  },
  "payment-terms": {
    catalogCode: "payment-terms",
    displayName: "Payment Terms",
    tableName: "core.PaymentTerms",
    idColumn: "PaymentTermId",
    codeColumn: "Code",
    nameColumn: "Name",
    descriptionColumn: "Description",
    allowedSearchColumns: ["Code", "Name", "Description"],
    allowedSortColumns: ["Code", "Name", "CreatedAt", "IsActive"],
    defaultSortBy: "Name",
    permissions: commonPermissions("master-data.payment-terms"),
    moduleCode: "master-data",
    tenantScoped: true,
    companyScoped: true,
    columns: {
      id: "PaymentTermId",
      tenantId: "TenantId",
      companyId: "CompanyId",
      code: "Code",
      name: "Name",
      description: "Description",
      isActive: "IsActive",
      createdAt: "CreatedAt",
      updatedAt: "UpdatedAt",
      createdBy: "CreatedBy",
      updatedBy: "UpdatedBy"
    },
    fields: commonCatalogFields(true)
  },
  "tax-categories": {
    catalogCode: "tax-categories",
    displayName: "Tax Categories",
    tableName: "fiscal.TaxCategories",
    idColumn: "TaxCategoryId",
    codeColumn: "Code",
    nameColumn: "Name",
    descriptionColumn: "Description",
    allowedSearchColumns: ["Code", "Name", "Description"],
    allowedSortColumns: ["Code", "Name", "CreatedAt", "IsActive"],
    defaultSortBy: "Name",
    permissions: commonPermissions("master-data.tax-categories"),
    moduleCode: "master-data",
    tenantScoped: true,
    companyScoped: true,
    columns: {
      id: "TaxCategoryId",
      tenantId: "TenantId",
      companyId: "CompanyId",
      code: "Code",
      name: "Name",
      description: "Description",
      isActive: "IsActive",
      createdAt: "CreatedAt",
      updatedAt: "UpdatedAt",
      createdBy: "CreatedBy",
      updatedBy: "UpdatedBy"
    },
    fields: commonCatalogFields(true)
  },
  "units-of-measure": {
    catalogCode: "units-of-measure",
    displayName: "Unidades de medida",
    tableName: "core.UnitsOfMeasure",
    idColumn: "UnitOfMeasureId",
    codeColumn: "Code",
    nameColumn: "Name",
    descriptionColumn: "Description",
    allowedSearchColumns: ["Code", "Name", "Description", "Symbol"],
    allowedSortColumns: ["Code", "Name", "CreatedAt", "IsActive"],
    defaultSortBy: "Name",
    permissions: commonPermissions("master-data.units-of-measure"),
    moduleCode: "master-data",
    tenantScoped: true,
    companyScoped: false,
    columns: {
      id: "UnitOfMeasureId",
      tenantId: "TenantId",
      companyId: "CompanyId",
      code: "Code",
      name: "Name",
      description: "Description",
      isActive: "IsActive",
      createdAt: "CreatedAt",
      updatedAt: "UpdatedAt",
      createdBy: "CreatedBy",
      updatedBy: "UpdatedBy"
    },
    fields: unitOfMeasureFields
  },
  customers: {
    catalogCode: "customers",
    displayName: "Clientes",
    tableName: "crm.Customers",
    idColumn: "CustomerId",
    codeColumn: "Code",
    nameColumn: "Name",
    allowedSearchColumns: ["Code", "Name", "CommercialName", "DocumentNumber", "Email", "Phone"],
    allowedSortColumns: [
      "Code",
      "Name",
      "CommercialName",
      "DocumentNumber",
      "Email",
      "City",
      "Province",
      "CreditLimit",
      "IsCreditCustomer",
      "CreatedAt",
      "IsActive"
    ],
    defaultSortBy: "Name",
    permissions: commonPermissions("crm.customers"),
    moduleCode: "crm",
    tenantScoped: true,
    companyScoped: true,
    columns: {
      id: "CustomerId",
      tenantId: "TenantId",
      companyId: "CompanyId",
      code: "Code",
      name: "Name",
      description: "AddressLine1",
      isActive: "IsActive",
      createdAt: "CreatedAt",
      updatedAt: "UpdatedAt",
      createdBy: "CreatedBy",
      updatedBy: "UpdatedBy"
    },
    fields: customerFields
  },
  suppliers: {
    catalogCode: "suppliers",
    displayName: "Proveedores",
    tableName: "purchasing.Suppliers",
    idColumn: "SupplierId",
    codeColumn: "Code",
    nameColumn: "Name",
    allowedSearchColumns: [
      "Code",
      "Name",
      "CommercialName",
      "DocumentNumber",
      "Email",
      "Phone",
      "ContactName"
    ],
    allowedSortColumns: [
      "Code",
      "Name",
      "CommercialName",
      "DocumentNumber",
      "Email",
      "City",
      "Province",
      "ContactName",
      "IsTaxWithholder",
      "IsForeignSupplier",
      "CreatedAt",
      "IsActive"
    ],
    defaultSortBy: "Name",
    permissions: commonPermissions("purchasing.suppliers"),
    moduleCode: "purchasing",
    tenantScoped: true,
    companyScoped: true,
    columns: {
      id: "SupplierId",
      tenantId: "TenantId",
      companyId: "CompanyId",
      code: "Code",
      name: "Name",
      description: "Notes",
      isActive: "IsActive",
      createdAt: "CreatedAt",
      updatedAt: "UpdatedAt",
      createdBy: "CreatedBy",
      updatedBy: "UpdatedBy"
    },
    fields: supplierFields
  },
  categories: {
    catalogCode: "categories",
    displayName: "Categorias",
    tableName: "inventory.Categories",
    idColumn: "CategoryId",
    codeColumn: "Code",
    nameColumn: "Name",
    descriptionColumn: "Description",
    allowedSearchColumns: ["Code", "Name", "Description"],
    allowedSortColumns: ["Code", "Name", "CreatedAt", "IsActive"],
    defaultSortBy: "Code",
    permissions: commonPermissions("inventory.categories"),
    moduleCode: "inventory",
    tenantScoped: true,
    companyScoped: true,
    columns: {
      id: "CategoryId",
      tenantId: "TenantId",
      companyId: "CompanyId",
      code: "Code",
      name: "Name",
      description: "Description",
      isActive: "IsActive",
      createdAt: "CreatedAt",
      updatedAt: "UpdatedAt",
      createdBy: "CreatedBy",
      updatedBy: "UpdatedBy"
    },
    fields: categoryFields
  },
  brands: {
    catalogCode: "brands",
    displayName: "Marcas",
    tableName: "inventory.Brands",
    idColumn: "BrandId",
    codeColumn: "Code",
    nameColumn: "Name",
    descriptionColumn: "Description",
    allowedSearchColumns: ["Code", "Name", "Description"],
    allowedSortColumns: ["Code", "Name", "CreatedAt", "IsActive"],
    defaultSortBy: "Code",
    permissions: commonPermissions("inventory.brands"),
    moduleCode: "inventory",
    tenantScoped: true,
    companyScoped: true,
    columns: {
      id: "BrandId",
      tenantId: "TenantId",
      companyId: "CompanyId",
      code: "Code",
      name: "Name",
      description: "Description",
      isActive: "IsActive",
      createdAt: "CreatedAt",
      updatedAt: "UpdatedAt",
      createdBy: "CreatedBy",
      updatedBy: "UpdatedBy"
    },
    fields: brandFields
  },
  warehouses: {
    catalogCode: "warehouses",
    displayName: "Almacenes",
    tableName: "inventory.Warehouses",
    idColumn: "WarehouseId",
    codeColumn: "Code",
    nameColumn: "Name",
    descriptionColumn: "Description",
    allowedSearchColumns: ["Code", "Name", "Description", "City", "Province"],
    allowedSortColumns: ["Code", "Name", "WarehouseType", "CreatedAt", "IsActive"],
    defaultSortBy: "Code",
    permissions: commonPermissions("inventory.warehouses"),
    moduleCode: "inventory",
    tenantScoped: true,
    companyScoped: true,
    columns: {
      id: "WarehouseId",
      tenantId: "TenantId",
      companyId: "CompanyId",
      code: "Code",
      name: "Name",
      description: "Description",
      isActive: "IsActive",
      createdAt: "CreatedAt",
      updatedAt: "UpdatedAt",
      createdBy: "CreatedBy",
      updatedBy: "UpdatedBy"
    },
    fields: warehouseFields
  },
  "inventory-stocks": {
    catalogCode: "inventory-stocks",
    displayName: "Existencias",
    tableName: "inventory.V_ItemStockSummary",
    idColumn: "ItemStockId",
    codeColumn: "ItemCode",
    nameColumn: "ItemDescription",
    descriptionColumn: "WarehouseName",
    allowedSearchColumns: ["ItemCode", "ItemDescription", "WarehouseCode", "WarehouseName"],
    allowedSortColumns: ["ItemCode", "WarehouseCode", "QuantityOnHand", "QuantityAvailable", "LastMovementAt", "IsActive"],
    defaultSortBy: "ItemCode",
    permissions: commonPermissions("inventory.stocks"),
    moduleCode: "inventory",
    tenantScoped: true,
    companyScoped: true,
    readOnly: true,
    columns: {
      id: "ItemStockId",
      tenantId: "TenantId",
      companyId: "CompanyId",
      code: "ItemCode",
      name: "ItemDescription",
      description: "WarehouseName",
      isActive: "IsActive",
      createdAt: "CreatedAt",
      updatedAt: "UpdatedAt",
      createdBy: "CreatedBy",
      updatedBy: "UpdatedBy"
    },
    fields: inventoryStockFields
  },
  "inventory-movements": {
    catalogCode: "inventory-movements",
    displayName: "Movimientos de inventario",
    tableName: "inventory.V_InventoryMovementSummary",
    idColumn: "InventoryMovementId",
    codeColumn: "MovementNumber",
    nameColumn: "MovementType",
    descriptionColumn: "Reference",
    allowedSearchColumns: ["MovementNumber", "MovementType", "Status", "SourceDocumentNumber", "Reference"],
    allowedSortColumns: ["MovementDate", "MovementNumber", "MovementType", "Status", "TotalQuantity", "TotalCost"],
    defaultSortBy: "MovementDate",
    permissions: commonPermissions("inventory.movements"),
    moduleCode: "inventory",
    tenantScoped: true,
    companyScoped: true,
    readOnly: true,
    columns: {
      id: "InventoryMovementId",
      tenantId: "TenantId",
      companyId: "CompanyId",
      code: "MovementNumber",
      name: "MovementType",
      description: "Reference",
      isActive: "IsActive",
      createdAt: "CreatedAt",
      updatedAt: "UpdatedAt",
      createdBy: "CreatedBy",
      updatedBy: "UpdatedBy"
    },
    fields: inventoryMovementFields
  },
  "inventory-movement-lines": {
    catalogCode: "inventory-movement-lines",
    displayName: "Lineas de movimientos de inventario",
    tableName: "inventory.V_InventoryMovementLineSummary",
    idColumn: "InventoryMovementLineId",
    codeColumn: "MovementNumber",
    nameColumn: "ItemDescription",
    descriptionColumn: "WarehouseName",
    allowedSearchColumns: ["MovementNumber", "MovementType", "Status", "ItemCode", "ItemDescription", "WarehouseCode"],
    allowedSortColumns: ["MovementNumber", "MovementType", "Status", "LineNumber", "ItemCode", "WarehouseCode", "Quantity", "UnitCost", "TotalCost"],
    defaultSortBy: "MovementNumber",
    permissions: commonPermissions("inventory.movements"),
    moduleCode: "inventory",
    tenantScoped: true,
    companyScoped: true,
    readOnly: true,
    columns: {
      id: "InventoryMovementLineId",
      tenantId: "TenantId",
      companyId: "CompanyId",
      code: "MovementNumber",
      name: "ItemDescription",
      description: "WarehouseName",
      isActive: "IsActive",
      createdAt: "CreatedAt",
      updatedAt: "UpdatedAt",
      createdBy: "CreatedBy",
      updatedBy: "UpdatedBy"
    },
    fields: inventoryMovementLineFields
  },
  "inventory-ledger": {
    catalogCode: "inventory-ledger",
    displayName: "Kardex",
    tableName: "inventory.V_InventoryLedger",
    idColumn: "InventoryLedgerEntryId",
    codeColumn: "MovementNumber",
    nameColumn: "ItemDescription",
    descriptionColumn: "WarehouseName",
    allowedSearchColumns: [
      "MovementNumber",
      "MovementType",
      "LedgerDirection",
      "ItemCode",
      "ItemDescription",
      "WarehouseCode",
      "WarehouseName",
      "SourceDocumentNumber",
      "Reference"
    ],
    allowedSortColumns: [
      "MovementDate",
      "PostedAt",
      "MovementNumber",
      "MovementType",
      "LedgerDirection",
      "ItemCode",
      "WarehouseCode",
      "QuantityIn",
      "QuantityOut",
      "QuantityBalanceImpact",
      "UnitCost",
      "TotalCost"
    ],
    defaultSortBy: "PostedAt",
    permissions: commonPermissions("inventory.ledger"),
    moduleCode: "inventory",
    tenantScoped: true,
    companyScoped: true,
    readOnly: true,
    columns: {
      id: "InventoryLedgerEntryId",
      tenantId: "TenantId",
      companyId: "CompanyId",
      code: "MovementNumber",
      name: "ItemDescription",
      description: "WarehouseName",
      isActive: "IsActive",
      createdAt: "CreatedAt",
      updatedAt: "UpdatedAt",
      createdBy: "CreatedBy",
      updatedBy: "UpdatedBy"
    },
    fields: inventoryLedgerFields
  },
  items: {
    catalogCode: "items",
    displayName: "Articulos",
    tableName: "inventory.Items",
    idColumn: "ItemId",
    codeColumn: "Code",
    nameColumn: "Description",
    allowedSearchColumns: ["Code", "Description", "Barcode", "AlternateCode"],
    allowedSortColumns: [
      "Code",
      "Description",
      "Barcode",
      "AlternateCode",
      "CategoryId",
      "BrandId",
      "BasePrice",
      "AverageCost",
      "CreatedAt",
      "IsActive"
    ],
    defaultSortBy: "Description",
    permissions: commonPermissions("inventory.items"),
    moduleCode: "inventory",
    tenantScoped: true,
    companyScoped: true,
    columns: {
      id: "ItemId",
      tenantId: "TenantId",
      companyId: "CompanyId",
      code: "Code",
      name: "Description",
      description: "Notes",
      isActive: "IsActive",
      createdAt: "CreatedAt",
      updatedAt: "UpdatedAt",
      createdBy: "CreatedBy",
      updatedBy: "UpdatedBy"
    },
    fields: itemFields
  }
} as const satisfies Record<string, CatalogDefinition>;

export type CatalogCode = keyof typeof catalogDefinitions;

export function getCatalogDefinition(catalogCode: string) {
  return catalogDefinitions[catalogCode as CatalogCode];
}
